groups:
- name: application_alerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
    for: 2m
    labels:
      severity: critical
      team: backend
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value }}% for the last 5 minutes"
      runbook_url: "https://wiki.company.com/runbooks/high-error-rate"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "High response time"
      description: "95th percentile response time is {{ $value }}s"
      runbook_url: "https://wiki.company.com/runbooks/high-response-time"

  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
      team: infrastructure
    annotations:
      summary: "Service is down"
      description: "Service {{ $labels.instance }} has been down for more than 1 minute"
      runbook_url: "https://wiki.company.com/runbooks/service-down"

  - alert: LowInventory
    expr: inventory_levels < 10
    for: 1m
    labels:
      severity: warning
      team: business
    annotations:
      summary: "Low inventory alert"
      description: "Product {{ $labels.product_id }} has only {{ $value }} items left"
      runbook_url: "https://wiki.company.com/runbooks/low-inventory"

- name: infrastructure_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "High CPU usage"
      description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"
      runbook_url: "https://wiki.company.com/runbooks/high-cpu"

  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 5m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "High memory usage"
      description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"
      runbook_url: "https://wiki.company.com/runbooks/high-memory"

  - alert: DiskSpaceLow
    expr: 100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes) > 90
    for: 5m
    labels:
      severity: critical
      team: infrastructure
    annotations:
      summary: "Disk space low"
      description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"
      runbook_url: "https://wiki.company.com/runbooks/disk-space-low"

  - alert: HighLoadAverage
    expr: node_load1 > 4
    for: 5m
    labels:
      severity: warning
      team: infrastructure
    annotations:
      summary: "High load average"
      description: "Load average is {{ $value }} on {{ $labels.instance }}"
      runbook_url: "https://wiki.company.com/runbooks/high-load"

- name: business_alerts
  rules:
  - alert: HighUserRegistrationRate
    expr: rate(user_registrations_total[1h]) > 100
    for: 10m
    labels:
      severity: info
      team: business
    annotations:
      summary: "High user registration rate"
      description: "User registration rate is {{ $value }} users/hour"
      runbook_url: "https://wiki.company.com/runbooks/high-registration-rate"

  - alert: APIUsageSpike
    expr: rate(api_calls_total[5m]) > 1000
    for: 5m
    labels:
      severity: warning
      team: backend
    annotations:
      summary: "API usage spike detected"
      description: "API calls per second is {{ $value }}"
      runbook_url: "https://wiki.company.com/runbooks/api-usage-spike"
